import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // add weights you use
  variable: "--font-poppins", // optional CSS variable
});

export const metadata: Metadata = {
  title: "Match Macking",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className={`${poppins.className } antialiased`}>
        {children}
      </body>
    </html>
  );
}